# Generated by Django 6.0.4 on 2026-05-07 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_notes', '0001_initial'),
        ('tasks', '0003_tasknote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnote',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noteroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteroom',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='private_note_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteroom',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_rooms', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='noteroom',
            name='visibility',
            field=models.CharField(choices=[('admin_only', 'Admin Only'), ('internal', 'Internal'), ('project_specific', 'Project Specific'), ('private', 'Private')], default='internal', max_length=20),
        ),
    ]
